// Stránka „Přehled" (vedení). Plocha je aktivní od kola 68; v kole 69 soubor nikdo nemění, výchozí
// rozložení se ladí v Nastavení → Stránky.
//
// Výchozí pro vedení je z katalogu, jen přibyl ukoly.dnes S, aby v kole 68 zůstala řada čísel
// (spec §6.1). Plánované widgety se vynechají, dokud je balík nedodá. Výchozí pro Provozní,
// Skladníka a Účetní platí jen s aspoň třemi viditelnými widgety (spec §1.3, pravidlo tří).
import type { DefiniceStranky } from '../typy.ts';

export const STRANKA: DefiniceStranky = {
  id: 'vedeni.prehled',
  rozhrani: 'vedeni',
  nazev: 'Přehled',
  pohled: 'overview',
  pristup: null,
  nastroj: null,
  inkoust: true,
  doporucene: [
    'prehled.ceka_na_tebe',
    'prehled.prvni_kroky',
    'pokladna.dnes',
    'pokladna.zive',
    'trzby.po_dnech',
    'trzby.top_produkty',
    'trzby.platby',
    'finance.souhrn_mesice',
    'finance.trzby_vs_mzdy',
    'finance.marze',
    'uzaverky.chybejici',
    'uzaverky.ke_schvaleni',
    'uzaverky.rozdil_kasy',
    'dochazka.prave_na_smene',
    'dochazka.dnes_v_podniku',
    'dochazka.moje_pichacky',
    'rozvrh.dnesni_smeny',
    'rozvrh.dostupnost_tymu',
    'rozvrh.diry',
    'rozvrh.zadosti_volno',
    'sklad.dochazi',
    'sklad.nakupni_seznam',
    'sklad.objednavky',
    'vyroba.k_vyrobe',
    'ukoly.dnes',
    'ukoly.po_terminu',
    'postupy.povinne_dnes',
    'hodnoceni.ohodnotit_smeny',
    'odmeny.zebricek',
    'akce.nejblizsi',
    'klient.hoste_vernost',
    'klient.dnesni_rezervace',
    'oznameni.nastenka',
    'chat.neprectene',
    'sdileni.pripnuta_nabidka',
    'organizace.podniky',
    'odkaz',
  ],
  vychozi: {
    'typ:vedeni': [
      { w: 'prehled.ceka_na_tebe', s: 'L' },
      { w: 'prehled.prvni_kroky', s: 'L' },
      { w: 'pokladna.dnes', s: 'M' },
      { w: 'dochazka.prave_na_smene', s: 'M' },
      { w: 'uzaverky.chybejici', s: 'S' },
      { w: 'ukoly.po_terminu', s: 'S' },
      { w: 'sklad.dochazi', s: 'S' },
      { w: 'ukoly.dnes', s: 'S' },
      { w: 'finance.trzby_vs_mzdy', s: 'S' },
      { w: 'rozvrh.dnesni_smeny', s: 'M' },
      { w: 'hodnoceni.ohodnotit_smeny', s: 'M' },
      { w: 'akce.nejblizsi', s: 'M' },
      { w: 'klient.hoste_vernost', s: 'M' },
      { w: 'oznameni.nastenka', s: 'L' },
      { w: 'rozvrh.dostupnost_tymu', s: 'M' },
      { w: 'dochazka.moje_pichacky', s: 'S' },
      { w: 'sdileni.pripnuta_nabidka', s: 'S' },
    ],
    'role:provozni': [
      { w: 'prehled.ceka_na_tebe', s: 'L' },
      { w: 'dochazka.prave_na_smene', s: 'M' },
      { w: 'rozvrh.dnesni_smeny', s: 'M' },
      { w: 'uzaverky.chybejici', s: 'S' },
      { w: 'uzaverky.ke_schvaleni', s: 'S' },
      { w: 'ukoly.po_terminu', s: 'S' },
      { w: 'sklad.dochazi', s: 'S' },
      { w: 'postupy.povinne_dnes', s: 'M' },
      { w: 'rozvrh.diry', s: 'M' },
      { w: 'hodnoceni.ohodnotit_smeny', s: 'L' },
      { w: 'akce.nejblizsi', s: 'M' },
      { w: 'oznameni.nastenka', s: 'M' },
    ],
    'role:skladnik': [
      { w: 'sklad.dochazi', s: 'L' },
      { w: 'sklad.nakupni_seznam', s: 'M' },
      { w: 'sklad.objednavky', s: 'M' },
      { w: 'sklad.navrhy', s: 'S' },
      { w: 'sklad.hlaseni', s: 'S' },
      { w: 'sklad.hodnota_zasob', s: 'S' },
      { w: 'sklad.inventura', s: 'S' },
      { w: 'vyroba.k_vyrobe', s: 'L' },
      { w: 'dochazka.moje_pichacky', s: 'M' },
      { w: 'sklad.posledni_pohyby', s: 'M' },
    ],
    'role:ucetni': [
      { w: 'finance.souhrn_mesice', s: 'L' },
      { w: 'finance.trzby_vs_mzdy', s: 'S' },
      { w: 'uzaverky.rozdil_kasy', s: 'S' },
      { w: 'finance.uctenky', s: 'S' },
      { w: 'finance.ztraty', s: 'S' },
      { w: 'trzby.po_dnech', s: 'L' },
      { w: 'finance.marze', s: 'M' },
      { w: 'uzaverky.chybejici', s: 'M' },
    ],
  },
  aktivni: true,
};
