// Stránka „Přehled" (zaměstnanec). Plocha je aktivní od kola 68; v kole 69 soubor nikdo nemění,
// výchozí rozložení se ladí v Nastavení → Stránky.
import type { DefiniceStranky } from '../typy.ts';

export const STRANKA: DefiniceStranky = {
  id: 'zamestnanec.domu',
  rozhrani: 'zamestnanec',
  nazev: 'Přehled',
  pohled: 'home',
  pristup: null,
  nastroj: null,
  doporucene: [
    'dochazka.moje_pichacky',
    'moje.nejblizsi_smena',
    'uzaverky.predavka',
    'klient.objednavky_od_stolu',
    'klient.dnesni_rezervace',
    'vyroba.k_vyrobe',
    'uzaverky.moje_uzaverka',
    'ukoly.dnes',
    'ukoly.po_terminu',
    'postupy.povinne_dnes',
    'moje.zpetna_vazba',
    'moje.uroven',
    'moje.tento_mesic',
    'moje.vydelek',
    'dochazka.moje_odpracovano',
    'oznameni.nastenka',
    'akce.nejblizsi',
    'rozvrh.pripominka_dostupnosti',
    'rozvrh.tym_nahled',
    'sklad.dochazi',
    'navody.povinne_cteni',
    'chat.neprectene',
    'sdileni.pripnuta_nabidka',
    'menu.vyprodano',
    'odkaz',
  ],
  vychozi: {
    'typ:zamestnanec': [
      { w: 'dochazka.moje_pichacky', s: 'M' },
      { w: 'moje.nejblizsi_smena', s: 'M' },
      { w: 'uzaverky.predavka', s: 'L' },
      { w: 'klient.objednavky_od_stolu', s: 'L' },
      { w: 'vyroba.k_vyrobe', s: 'L' },
      { w: 'uzaverky.moje_uzaverka', s: 'M' },
      { w: 'ukoly.dnes', s: 'M' },
      { w: 'moje.zpetna_vazba', s: 'M' },
      { w: 'postupy.povinne_dnes', s: 'M' },
      { w: 'oznameni.nastenka', s: 'L' },
      { w: 'akce.nejblizsi', s: 'M' },
      { w: 'rozvrh.pripominka_dostupnosti', s: 'M' },
      { w: 'sklad.dochazi', s: 'M' },
      { w: 'chat.neprectene', s: 'S' },
      { w: 'dochazka.moje_odpracovano', s: 'S' },
      { w: 'moje.tento_mesic', s: 'M' },
      { w: 'sdileni.pripnuta_nabidka', s: 'M' },
    ],
  },
  aktivni: true,
};
